import {
  SiCss3,
  SiFigma,
  SiGit,
  SiHtml5,
  SiJavascript,
  SiNextdotjs,
  SiNodedotjs,
  SiMui,
  SiShadcnui,
  SiReact,
  SiReactquery,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiSass,
  SiStyledcomponents,
  SiGithub,
  SiGitlab,
  SiRedux,
  SiPnpm,
  SiVercel,
  SiAwsamplify,
  SiFramer,
  SiGoogleads,
  SiGoogleanalytics,
  SiStripe,
  SiContentful,
  SiSanity,
  SiRetool,
  SiGoogletagmanager,
} from '@icons-pack/react-simple-icons';

export const DATA = [
  {
    label: 'React',
    icon: <SiReact />,
    url: 'https://react.dev/',
  },
  {
    label: 'HTML',
    icon: <SiHtml5 />,
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
  },
  {
    label: 'CSS',
    icon: <SiCss3 />,
    url: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
  },
  {
    label: 'JavaScript',
    icon: <SiJavascript />,
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  },
  { label: 'TypeScript', icon: <SiTypescript />, url: 'https://www.typescriptlang.org/' },
  { label: 'Next.js', icon: <SiNextdotjs />, url: 'https://nextjs.org/' },
  { label: 'Node.js', icon: <SiNodedotjs />, url: 'https://nodejs.org/en' },
  { label: 'Tailwind CSS', icon: <SiTailwindcss />, url: 'https://tailwindcss.com/' },
  { label: 'Shadcn', icon: <SiShadcnui />, url: 'https://ui.shadcn.com/' },
  { label: 'Material UI', icon: <SiMui />, url: 'https://mui.com/' },
  { label: 'Sass', icon: <SiSass />, url: 'https://sass-lang.com/' },
  {
    label: 'Styled Components',
    icon: <SiStyledcomponents />,
    url: 'https://styled-components.com/',
  },
  { label: 'Git', icon: <SiGit />, url: 'https://git-scm.com/' },
  { label: 'GitHub', icon: <SiGithub />, url: 'https://www.github.com/' },
  { label: 'GitLab', icon: <SiGitlab />, url: 'https://about.gitlab.com/' },
  {
    label: 'Tanstack Query',
    icon: <SiReactquery />,
    url: 'https://tanstack.com/query/latest',
  },
  { label: 'Redux', icon: <SiRedux />, url: 'https://redux.js.org/' },
  { label: 'Zustand', icon: <p>Zustand</p>, url: 'https://zustand-demo.pmnd.rs/' },
  { label: 'Framer Motion', icon: <SiFramer />, url: 'https://www.framer.com/docs/' },
  {
    label: 'Google Ad manager',
    icon: <SiGoogleads />,
    url: 'https://admanager.google.com/intl/es/home/',
  },
  {
    label: 'Google Analytics',
    icon: <SiGoogleanalytics />,
    url: 'https://analytics.google.com/',
  },
  {
    label: 'Google Tag Manager',
    icon: <SiGoogletagmanager />,
    url: 'https://tagmanager.google.com/',
  },
  { label: 'Stripe', icon: <SiStripe />, url: 'https://stripe.com/' },
  { label: 'Contentful', icon: <SiContentful />, url: 'https://www.contentful.com/' },
  { label: 'Sanity', icon: <SiSanity />, url: 'https://www.sanity.io/' },
  { label: 'React Native', icon: <SiReact />, url: 'https://reactnative.dev/' },
  { label: 'Vite', icon: <SiVite />, url: 'https://vitejs.dev/' },
  { label: 'pnpm', icon: <SiPnpm />, url: 'https://pnpm.io/' },
  { label: 'Vercel', icon: <SiVercel />, url: 'https://vercel.com/' },
  {
    label: 'AWS Amplify',
    icon: <SiAwsamplify />,
    url: 'https://aws.amazon.com/amplify/',
  },
  { label: 'Figma', icon: <SiFigma />, url: 'https://www.figma.com/' },
  { label: 'Retool', icon: <SiRetool />, url: 'https://retool.com/' },
];
